SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
BG_COLOR = "black"

SEGMENT_SIZE = 20
MOVE_DISTANCE = SEGMENT_SIZE

STARTING_POSITIONS = [(0, 0), (-SEGMENT_SIZE, 0), (-2 * SEGMENT_SIZE, 0)]

UP = 90
DOWN = 270
LEFT = 180
RIGHT = 0

WALL_MARGIN = 12
BORDER_X = SCREEN_WIDTH // 2 - WALL_MARGIN
BORDER_Y = SCREEN_HEIGHT // 2 - WALL_MARGIN

SCORE_MARGIN = 40
SCORE_Y = SCREEN_HEIGHT // 2 - SCORE_MARGIN

_HALF_SEGMENT = SEGMENT_SIZE // 2
FOOD_X_BOUND = BORDER_X - _HALF_SEGMENT
FOOD_Y_MIN = -(BORDER_Y - _HALF_SEGMENT)
FOOD_Y_MAX = SCORE_Y - SEGMENT_SIZE

STARTING_SLEEP_DELAY = 0.1
MINIMUM_SLEEP_DELAY = 0.05
SPEED_INCREMENT = 0.01

FOOD_OPTIONS = [
    ("red", 1),
    ("yellow", 3),
    ("green", 5),
]

DEFAULT_SHAPE_SIZE = 20
FOOD_SIZE = DEFAULT_SHAPE_SIZE - 3
FOOD_SHAPE_STRETCH = FOOD_SIZE / DEFAULT_SHAPE_SIZE
